# Generated by Django 5.2 on 2025-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Имя_поста")),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="post")),
                ("publication", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["description", "views"],
            },
        ),
    ]
