# Generated by Django 5.2 on 2025-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Изображение", null=True, upload_to="product"
            ),
        ),
    ]
