# Generated by Django 5.2 on 2025-05-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descriptions",
            new_name="description",
        ),
    ]
