# Generated by Django 5.2 on 2025-05-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_descriptions_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="descriptions",
            field=models.TextField(verbose_name="Описание категории"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_category",
            field=models.CharField(
                max_length=150, verbose_name="Наименование категории"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Описание продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Наименование продукта"
            ),
        ),
    ]
